*** Settings ***
Resource    ../page/page.robot

*** Tasks ***
Send test email
    Authorize       account=${USERNAME}    password=${PASSWORD}
    Send Message    sender=${USERNAME}
    ...    recipients=${RECIPIENT}
    ...    subject=[KBTG] Message generated by robot
    ...    body=This is the body of the email.